version: '3.8'

services:
  backend:
    image: niishantdev/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

  frontend:
    image: niishantdev/frontend:latest
    container_name: frontend
    ports:
      - "4200:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

